-- ============================================================
-- 003_foreign_keys.sql
-- Regenerated squash — Batch 3: FK constraints (after all tables exist)
-- ============================================================

alter table public.billing_entries add constraint billing_entries_bill_to_client_fk FOREIGN KEY (bill_to_case_client_id) REFERENCES case_clients(id) ON DELETE SET NULL;
alter table public.billing_entries add constraint billing_entries_bill_to_org_fk FOREIGN KEY (bill_to_case_organization_id) REFERENCES case_organizations(id) ON DELETE SET NULL;
alter table public.billing_entries add constraint billing_entries_billing_owner_fk FOREIGN KEY (billing_owner_case_organization_id) REFERENCES case_organizations(id) ON DELETE SET NULL;
alter table public.billing_entries add constraint billing_entries_case_id_fkey FOREIGN KEY (case_id) REFERENCES cases(id) ON DELETE CASCADE;
alter table public.billing_entries add constraint billing_entries_created_by_fkey FOREIGN KEY (created_by) REFERENCES profiles(id) ON DELETE SET NULL;
alter table public.billing_entries add constraint billing_entries_fee_agreement_fk FOREIGN KEY (fee_agreement_id) REFERENCES fee_agreements(id) ON DELETE SET NULL;
alter table public.billing_entries add constraint billing_entries_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES organizations(id) ON DELETE CASCADE;
alter table public.billing_entries add constraint billing_entries_updated_by_fkey FOREIGN KEY (updated_by) REFERENCES profiles(id) ON DELETE SET NULL;
alter table public.billing_subscription_events add constraint billing_subscription_events_created_by_fkey FOREIGN KEY (created_by) REFERENCES profiles(id) ON DELETE SET NULL;
alter table public.billing_subscription_events add constraint billing_subscription_events_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES organizations(id) ON DELETE CASCADE;
alter table public.case_clients add constraint case_clients_case_id_fkey FOREIGN KEY (case_id) REFERENCES cases(id) ON DELETE CASCADE;
alter table public.case_clients add constraint case_clients_created_by_fkey FOREIGN KEY (created_by) REFERENCES profiles(id) ON DELETE SET NULL;
alter table public.case_clients add constraint case_clients_last_linked_hub_id_fkey FOREIGN KEY (last_linked_hub_id) REFERENCES case_hubs(id) ON DELETE SET NULL;
alter table public.case_clients add constraint case_clients_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES organizations(id) ON DELETE CASCADE;
alter table public.case_clients add constraint case_clients_profile_id_fkey FOREIGN KEY (profile_id) REFERENCES profiles(id) ON DELETE SET NULL;
alter table public.case_clients add constraint case_clients_updated_by_fkey FOREIGN KEY (updated_by) REFERENCES profiles(id) ON DELETE SET NULL;
alter table public.case_document_reviews add constraint case_document_reviews_case_document_id_fkey FOREIGN KEY (case_document_id) REFERENCES case_documents(id) ON DELETE CASCADE;
alter table public.case_document_reviews add constraint case_document_reviews_case_id_fkey FOREIGN KEY (case_id) REFERENCES cases(id) ON DELETE CASCADE;
alter table public.case_document_reviews add constraint case_document_reviews_decided_by_fkey FOREIGN KEY (decided_by) REFERENCES profiles(id) ON DELETE SET NULL;
alter table public.case_document_reviews add constraint case_document_reviews_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES organizations(id) ON DELETE CASCADE;
alter table public.case_document_reviews add constraint case_document_reviews_requested_by_fkey FOREIGN KEY (requested_by) REFERENCES profiles(id) ON DELETE SET NULL;
alter table public.case_documents add constraint case_documents_approval_requested_by_fkey FOREIGN KEY (approval_requested_by) REFERENCES profiles(id) ON DELETE SET NULL;
alter table public.case_documents add constraint case_documents_case_id_fkey FOREIGN KEY (case_id) REFERENCES cases(id) ON DELETE CASCADE;
alter table public.case_documents add constraint case_documents_created_by_fkey FOREIGN KEY (created_by) REFERENCES profiles(id) ON DELETE SET NULL;
alter table public.case_documents add constraint case_documents_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES organizations(id) ON DELETE CASCADE;
alter table public.case_documents add constraint case_documents_reviewed_by_fkey FOREIGN KEY (reviewed_by) REFERENCES profiles(id) ON DELETE SET NULL;
alter table public.case_documents add constraint case_documents_updated_by_fkey FOREIGN KEY (updated_by) REFERENCES profiles(id) ON DELETE SET NULL;
alter table public.case_handlers add constraint case_handlers_case_id_fkey FOREIGN KEY (case_id) REFERENCES cases(id) ON DELETE CASCADE;
alter table public.case_handlers add constraint case_handlers_created_by_fkey FOREIGN KEY (created_by) REFERENCES profiles(id) ON DELETE SET NULL;
alter table public.case_handlers add constraint case_handlers_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES organizations(id) ON DELETE CASCADE;
alter table public.case_handlers add constraint case_handlers_profile_id_fkey FOREIGN KEY (profile_id) REFERENCES profiles(id) ON DELETE SET NULL;
alter table public.case_handlers add constraint case_handlers_updated_by_fkey FOREIGN KEY (updated_by) REFERENCES profiles(id) ON DELETE SET NULL;
alter table public.case_hub_activity add constraint case_hub_activity_actor_profile_id_fkey FOREIGN KEY (actor_profile_id) REFERENCES profiles(id) ON DELETE SET NULL;
alter table public.case_hub_activity add constraint case_hub_activity_hub_id_fkey FOREIGN KEY (hub_id) REFERENCES case_hubs(id) ON DELETE CASCADE;
alter table public.case_hub_members add constraint case_hub_members_hub_id_fkey FOREIGN KEY (hub_id) REFERENCES case_hubs(id) ON DELETE CASCADE;
alter table public.case_hub_members add constraint case_hub_members_profile_id_fkey FOREIGN KEY (profile_id) REFERENCES profiles(id) ON DELETE CASCADE;
alter table public.case_hub_organizations add constraint case_hub_organizations_created_by_fkey FOREIGN KEY (created_by) REFERENCES profiles(id) ON DELETE SET NULL;
alter table public.case_hub_organizations add constraint case_hub_organizations_hub_id_fkey FOREIGN KEY (hub_id) REFERENCES case_hubs(id) ON DELETE CASCADE;
alter table public.case_hub_organizations add constraint case_hub_organizations_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES organizations(id) ON DELETE CASCADE;
alter table public.case_hub_organizations add constraint case_hub_organizations_source_case_organization_id_fkey FOREIGN KEY (source_case_organization_id) REFERENCES case_organizations(id) ON DELETE SET NULL;
alter table public.case_hub_organizations add constraint case_hub_organizations_updated_by_fkey FOREIGN KEY (updated_by) REFERENCES profiles(id) ON DELETE SET NULL;
alter table public.case_hubs add constraint case_hubs_case_id_fkey FOREIGN KEY (case_id) REFERENCES cases(id) ON DELETE CASCADE;
alter table public.case_hubs add constraint case_hubs_created_by_fkey FOREIGN KEY (created_by) REFERENCES profiles(id) ON DELETE SET NULL;
alter table public.case_hubs add constraint case_hubs_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES organizations(id) ON DELETE CASCADE;
alter table public.case_hubs add constraint case_hubs_primary_case_client_id_fkey FOREIGN KEY (primary_case_client_id) REFERENCES case_clients(id) ON DELETE SET NULL NOT VALID;
alter table public.case_hubs add constraint case_hubs_primary_client_id_fkey FOREIGN KEY (primary_client_id) REFERENCES profiles(id) ON DELETE SET NULL;
alter table public.case_messages add constraint case_messages_case_id_fkey FOREIGN KEY (case_id) REFERENCES cases(id) ON DELETE CASCADE;
alter table public.case_messages add constraint case_messages_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES organizations(id) ON DELETE CASCADE;
alter table public.case_messages add constraint case_messages_sender_profile_id_fkey FOREIGN KEY (sender_profile_id) REFERENCES profiles(id) ON DELETE CASCADE;
alter table public.case_organizations add constraint case_organizations_case_id_fkey FOREIGN KEY (case_id) REFERENCES cases(id) ON DELETE CASCADE;
alter table public.case_organizations add constraint case_organizations_created_by_fkey FOREIGN KEY (created_by) REFERENCES profiles(id) ON DELETE SET NULL;
alter table public.case_organizations add constraint case_organizations_instructed_by_case_organization_id_fkey FOREIGN KEY (instructed_by_case_organization_id) REFERENCES case_organizations(id) ON DELETE SET NULL;
alter table public.case_organizations add constraint case_organizations_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES organizations(id) ON DELETE CASCADE;
alter table public.case_organizations add constraint case_organizations_updated_by_fkey FOREIGN KEY (updated_by) REFERENCES profiles(id) ON DELETE SET NULL;
alter table public.case_parties add constraint case_parties_case_id_fkey FOREIGN KEY (case_id) REFERENCES cases(id) ON DELETE CASCADE;
alter table public.case_parties add constraint case_parties_created_by_fkey FOREIGN KEY (created_by) REFERENCES profiles(id) ON DELETE SET NULL;
alter table public.case_parties add constraint case_parties_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES organizations(id) ON DELETE CASCADE;
alter table public.case_parties add constraint case_parties_updated_by_fkey FOREIGN KEY (updated_by) REFERENCES profiles(id) ON DELETE SET NULL;
alter table public.case_party_private_profiles add constraint case_party_private_profiles_case_id_fkey FOREIGN KEY (case_id) REFERENCES cases(id) ON DELETE CASCADE;
alter table public.case_party_private_profiles add constraint case_party_private_profiles_case_party_id_fkey FOREIGN KEY (case_party_id) REFERENCES case_parties(id) ON DELETE CASCADE;
alter table public.case_party_private_profiles add constraint case_party_private_profiles_created_by_fkey FOREIGN KEY (created_by) REFERENCES profiles(id) ON DELETE SET NULL;
alter table public.case_party_private_profiles add constraint case_party_private_profiles_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES organizations(id) ON DELETE CASCADE;
alter table public.case_party_private_profiles add constraint case_party_private_profiles_updated_by_fkey FOREIGN KEY (updated_by) REFERENCES profiles(id) ON DELETE SET NULL;
alter table public.case_recovery_activities add constraint case_recovery_activities_case_id_fkey FOREIGN KEY (case_id) REFERENCES cases(id) ON DELETE CASCADE;
alter table public.case_recovery_activities add constraint case_recovery_activities_created_by_fkey FOREIGN KEY (created_by) REFERENCES profiles(id) ON DELETE SET NULL;
alter table public.case_recovery_activities add constraint case_recovery_activities_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES organizations(id) ON DELETE CASCADE;
alter table public.case_recovery_activities add constraint case_recovery_activities_updated_by_fkey FOREIGN KEY (updated_by) REFERENCES profiles(id) ON DELETE SET NULL;
alter table public.case_request_attachments add constraint case_request_attachments_case_id_fkey FOREIGN KEY (case_id) REFERENCES cases(id) ON DELETE CASCADE;
alter table public.case_request_attachments add constraint case_request_attachments_case_request_id_fkey FOREIGN KEY (case_request_id) REFERENCES case_requests(id) ON DELETE CASCADE;
alter table public.case_request_attachments add constraint case_request_attachments_created_by_fkey FOREIGN KEY (created_by) REFERENCES profiles(id) ON DELETE SET NULL;
alter table public.case_request_attachments add constraint case_request_attachments_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES organizations(id) ON DELETE CASCADE;
alter table public.case_requests add constraint case_requests_assigned_to_fkey FOREIGN KEY (assigned_to) REFERENCES profiles(id) ON DELETE SET NULL;
alter table public.case_requests add constraint case_requests_case_id_fkey FOREIGN KEY (case_id) REFERENCES cases(id) ON DELETE CASCADE;
alter table public.case_requests add constraint case_requests_created_by_fkey FOREIGN KEY (created_by) REFERENCES profiles(id) ON DELETE CASCADE;
alter table public.case_requests add constraint case_requests_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES organizations(id) ON DELETE CASCADE;
alter table public.case_schedules add constraint case_schedules_case_id_fkey FOREIGN KEY (case_id) REFERENCES cases(id) ON DELETE CASCADE;
alter table public.case_schedules add constraint case_schedules_created_by_fkey FOREIGN KEY (created_by) REFERENCES profiles(id) ON DELETE SET NULL;
alter table public.case_schedules add constraint case_schedules_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES organizations(id) ON DELETE CASCADE;
alter table public.case_schedules add constraint case_schedules_updated_by_fkey FOREIGN KEY (updated_by) REFERENCES profiles(id) ON DELETE SET NULL;
alter table public.case_stage_template_steps add constraint case_stage_template_steps_template_id_fkey FOREIGN KEY (template_id) REFERENCES case_stage_templates(id) ON DELETE CASCADE;
alter table public.case_stage_templates add constraint case_stage_templates_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES organizations(id) ON DELETE CASCADE;
alter table public.case_type_default_modules add constraint case_type_default_modules_module_key_fkey FOREIGN KEY (module_key) REFERENCES case_module_catalog(module_key) ON DELETE CASCADE;
alter table public.cases add constraint cases_created_by_fkey FOREIGN KEY (created_by) REFERENCES profiles(id) ON DELETE SET NULL;
alter table public.cases add constraint cases_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES organizations(id) ON DELETE CASCADE;
alter table public.cases add constraint cases_updated_by_fkey FOREIGN KEY (updated_by) REFERENCES profiles(id) ON DELETE SET NULL;
alter table public.client_access_requests add constraint client_access_requests_requester_profile_id_fkey FOREIGN KEY (requester_profile_id) REFERENCES profiles(id) ON DELETE CASCADE;
alter table public.client_access_requests add constraint client_access_requests_reviewed_by_fkey FOREIGN KEY (reviewed_by) REFERENCES profiles(id) ON DELETE SET NULL;
alter table public.client_access_requests add constraint client_access_requests_target_organization_id_fkey FOREIGN KEY (target_organization_id) REFERENCES organizations(id) ON DELETE CASCADE;
alter table public.client_private_profiles add constraint client_private_profiles_created_by_fkey FOREIGN KEY (created_by) REFERENCES profiles(id) ON DELETE SET NULL;
alter table public.client_private_profiles add constraint client_private_profiles_profile_id_fkey FOREIGN KEY (profile_id) REFERENCES profiles(id) ON DELETE CASCADE;
alter table public.client_private_profiles add constraint client_private_profiles_updated_by_fkey FOREIGN KEY (updated_by) REFERENCES profiles(id) ON DELETE SET NULL;
alter table public.client_service_requests add constraint client_service_requests_created_by_fkey FOREIGN KEY (created_by) REFERENCES profiles(id) ON DELETE SET NULL;
alter table public.client_service_requests add constraint client_service_requests_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES organizations(id) ON DELETE SET NULL;
alter table public.client_service_requests add constraint client_service_requests_profile_id_fkey FOREIGN KEY (profile_id) REFERENCES profiles(id) ON DELETE CASCADE;
alter table public.client_service_requests add constraint client_service_requests_updated_by_fkey FOREIGN KEY (updated_by) REFERENCES profiles(id) ON DELETE SET NULL;
alter table public.client_temp_credentials add constraint client_temp_credentials_case_id_fkey FOREIGN KEY (case_id) REFERENCES cases(id) ON DELETE SET NULL;
alter table public.client_temp_credentials add constraint client_temp_credentials_issued_by_fkey FOREIGN KEY (issued_by) REFERENCES profiles(id) ON DELETE SET NULL;
alter table public.client_temp_credentials add constraint client_temp_credentials_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES organizations(id) ON DELETE SET NULL;
alter table public.client_temp_credentials add constraint client_temp_credentials_profile_id_fkey FOREIGN KEY (profile_id) REFERENCES profiles(id) ON DELETE CASCADE;
alter table public.collection_compensation_entries add constraint collection_compensation_entri_collection_compensation_plan_fkey FOREIGN KEY (collection_compensation_plan_version_id) REFERENCES collection_compensation_plan_versions(id) ON DELETE CASCADE;
alter table public.collection_compensation_entries add constraint collection_compensation_entries_case_id_fkey FOREIGN KEY (case_id) REFERENCES cases(id) ON DELETE CASCADE;
alter table public.collection_compensation_plan_versions add constraint collection_compensation_plan__collection_compensation_plan_fkey FOREIGN KEY (collection_compensation_plan_id) REFERENCES collection_compensation_plans(id) ON DELETE CASCADE;
alter table public.collection_compensation_plan_versions add constraint collection_compensation_plan_versions_fixed_by_fkey FOREIGN KEY (fixed_by) REFERENCES profiles(id) ON DELETE SET NULL;
alter table public.collection_compensation_plans add constraint collection_compensation_plans_beneficiary_case_organizatio_fkey FOREIGN KEY (beneficiary_case_organization_id) REFERENCES case_organizations(id) ON DELETE SET NULL;
alter table public.collection_compensation_plans add constraint collection_compensation_plans_beneficiary_membership_id_fkey FOREIGN KEY (beneficiary_membership_id) REFERENCES organization_memberships(id) ON DELETE SET NULL;
alter table public.collection_compensation_plans add constraint collection_compensation_plans_case_id_fkey FOREIGN KEY (case_id) REFERENCES cases(id) ON DELETE CASCADE;
alter table public.collection_compensation_plans add constraint collection_compensation_plans_collection_org_case_organiza_fkey FOREIGN KEY (collection_org_case_organization_id) REFERENCES case_organizations(id) ON DELETE CASCADE;
alter table public.collection_compensation_plans add constraint collection_compensation_plans_created_by_fkey FOREIGN KEY (created_by) REFERENCES profiles(id) ON DELETE SET NULL;
alter table public.collection_compensation_plans add constraint collection_compensation_plans_updated_by_fkey FOREIGN KEY (updated_by) REFERENCES profiles(id) ON DELETE SET NULL;
alter table public.collection_payouts add constraint collection_payouts_collection_compensation_entry_id_fkey FOREIGN KEY (collection_compensation_entry_id) REFERENCES collection_compensation_entries(id) ON DELETE CASCADE;
alter table public.collection_payouts add constraint collection_payouts_created_by_fkey FOREIGN KEY (created_by) REFERENCES profiles(id) ON DELETE SET NULL;
alter table public.collection_performance_daily add constraint collection_performance_daily_case_id_fkey FOREIGN KEY (case_id) REFERENCES cases(id) ON DELETE CASCADE;
alter table public.collection_performance_daily add constraint collection_performance_daily_collection_org_case_organizat_fkey FOREIGN KEY (collection_org_case_organization_id) REFERENCES case_organizations(id) ON DELETE CASCADE;
alter table public.collection_performance_daily add constraint collection_performance_daily_organization_membership_id_fkey FOREIGN KEY (organization_membership_id) REFERENCES organization_memberships(id) ON DELETE SET NULL;
alter table public.content_resources add constraint content_resources_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES organizations(id) ON DELETE CASCADE;
alter table public.content_resources add constraint content_resources_updated_by_fkey FOREIGN KEY (updated_by) REFERENCES profiles(id) ON DELETE SET NULL;
alter table public.document_ingestion_jobs add constraint document_ingestion_jobs_case_document_id_fkey FOREIGN KEY (case_document_id) REFERENCES case_documents(id) ON DELETE SET NULL;
alter table public.document_ingestion_jobs add constraint document_ingestion_jobs_case_id_fkey FOREIGN KEY (case_id) REFERENCES cases(id) ON DELETE CASCADE;
alter table public.document_ingestion_jobs add constraint document_ingestion_jobs_created_by_fkey FOREIGN KEY (created_by) REFERENCES profiles(id) ON DELETE SET NULL;
alter table public.document_ingestion_jobs add constraint document_ingestion_jobs_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES organizations(id) ON DELETE CASCADE;
alter table public.document_ingestion_jobs add constraint document_ingestion_jobs_updated_by_fkey FOREIGN KEY (updated_by) REFERENCES profiles(id) ON DELETE SET NULL;
alter table public.feature_flags add constraint feature_flags_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES organizations(id) ON DELETE CASCADE;
alter table public.feature_flags add constraint feature_flags_updated_by_fkey FOREIGN KEY (updated_by) REFERENCES profiles(id) ON DELETE SET NULL;
alter table public.fee_agreements add constraint fee_agreements_bill_to_case_client_id_fkey FOREIGN KEY (bill_to_case_client_id) REFERENCES case_clients(id) ON DELETE SET NULL;
alter table public.fee_agreements add constraint fee_agreements_bill_to_case_organization_id_fkey FOREIGN KEY (bill_to_case_organization_id) REFERENCES case_organizations(id) ON DELETE SET NULL;
alter table public.fee_agreements add constraint fee_agreements_billing_owner_case_organization_id_fkey FOREIGN KEY (billing_owner_case_organization_id) REFERENCES case_organizations(id) ON DELETE CASCADE;
alter table public.fee_agreements add constraint fee_agreements_case_id_fkey FOREIGN KEY (case_id) REFERENCES cases(id) ON DELETE CASCADE;
alter table public.fee_agreements add constraint fee_agreements_created_by_fkey FOREIGN KEY (created_by) REFERENCES profiles(id) ON DELETE SET NULL;
alter table public.fee_agreements add constraint fee_agreements_updated_by_fkey FOREIGN KEY (updated_by) REFERENCES profiles(id) ON DELETE SET NULL;
alter table public.insolvency_client_action_items add constraint insolvency_action_items_case_org_fk FOREIGN KEY (case_id, organization_id) REFERENCES cases(id, organization_id) ON DELETE CASCADE;
alter table public.insolvency_client_action_items add constraint insolvency_client_action_items_case_id_fkey FOREIGN KEY (case_id) REFERENCES cases(id) ON DELETE CASCADE;
alter table public.insolvency_client_action_items add constraint insolvency_client_action_items_client_checked_by_fkey FOREIGN KEY (client_checked_by) REFERENCES profiles(id) ON DELETE SET NULL;
alter table public.insolvency_client_action_items add constraint insolvency_client_action_items_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES organizations(id) ON DELETE CASCADE;
alter table public.insolvency_client_action_items add constraint insolvency_client_action_items_packet_id_fkey FOREIGN KEY (packet_id) REFERENCES insolvency_client_action_packets(id) ON DELETE CASCADE;
alter table public.insolvency_client_action_items add constraint insolvency_client_action_items_staff_verified_by_fkey FOREIGN KEY (staff_verified_by) REFERENCES profiles(id) ON DELETE SET NULL;
alter table public.insolvency_client_action_packets add constraint insolvency_action_packets_case_org_fk FOREIGN KEY (case_id, organization_id) REFERENCES cases(id, organization_id) ON DELETE CASCADE;
alter table public.insolvency_client_action_packets add constraint insolvency_client_action_packets_case_id_fkey FOREIGN KEY (case_id) REFERENCES cases(id) ON DELETE CASCADE;
alter table public.insolvency_client_action_packets add constraint insolvency_client_action_packets_created_by_fkey FOREIGN KEY (created_by) REFERENCES profiles(id) ON DELETE SET NULL;
alter table public.insolvency_client_action_packets add constraint insolvency_client_action_packets_ingestion_job_id_fkey FOREIGN KEY (ingestion_job_id) REFERENCES document_ingestion_jobs(id) ON DELETE SET NULL;
alter table public.insolvency_client_action_packets add constraint insolvency_client_action_packets_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES organizations(id) ON DELETE CASCADE;
alter table public.insolvency_client_action_packets add constraint insolvency_client_action_packets_updated_by_fkey FOREIGN KEY (updated_by) REFERENCES profiles(id) ON DELETE SET NULL;
alter table public.insolvency_collaterals add constraint insolvency_collaterals_case_id_fkey FOREIGN KEY (case_id) REFERENCES cases(id) ON DELETE CASCADE;
alter table public.insolvency_collaterals add constraint insolvency_collaterals_case_org_fk FOREIGN KEY (case_id, organization_id) REFERENCES cases(id, organization_id) ON DELETE CASCADE;
alter table public.insolvency_collaterals add constraint insolvency_collaterals_created_by_fkey FOREIGN KEY (created_by) REFERENCES profiles(id) ON DELETE SET NULL;
alter table public.insolvency_collaterals add constraint insolvency_collaterals_creditor_id_fkey FOREIGN KEY (creditor_id) REFERENCES insolvency_creditors(id) ON DELETE CASCADE;
alter table public.insolvency_collaterals add constraint insolvency_collaterals_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES organizations(id) ON DELETE CASCADE;
alter table public.insolvency_collaterals add constraint insolvency_collaterals_updated_by_fkey FOREIGN KEY (updated_by) REFERENCES profiles(id) ON DELETE SET NULL;
alter table public.insolvency_creditor_addresses add constraint insolvency_creditor_addresses_created_by_fkey FOREIGN KEY (created_by) REFERENCES profiles(id) ON DELETE SET NULL;
alter table public.insolvency_creditor_addresses add constraint insolvency_creditor_addresses_creditor_id_fkey FOREIGN KEY (creditor_id) REFERENCES insolvency_creditors(id) ON DELETE CASCADE;
alter table public.insolvency_creditor_addresses add constraint insolvency_creditor_addresses_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES organizations(id) ON DELETE CASCADE;
alter table public.insolvency_creditors add constraint insolvency_creditors_case_id_fkey FOREIGN KEY (case_id) REFERENCES cases(id) ON DELETE CASCADE;
alter table public.insolvency_creditors add constraint insolvency_creditors_case_org_fk FOREIGN KEY (case_id, organization_id) REFERENCES cases(id, organization_id) ON DELETE CASCADE;
alter table public.insolvency_creditors add constraint insolvency_creditors_confirmed_by_fkey FOREIGN KEY (confirmed_by) REFERENCES profiles(id) ON DELETE SET NULL;
alter table public.insolvency_creditors add constraint insolvency_creditors_created_by_fkey FOREIGN KEY (created_by) REFERENCES profiles(id) ON DELETE SET NULL;
alter table public.insolvency_creditors add constraint insolvency_creditors_ingestion_job_id_fkey FOREIGN KEY (ingestion_job_id) REFERENCES document_ingestion_jobs(id) ON DELETE SET NULL;
alter table public.insolvency_creditors add constraint insolvency_creditors_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES organizations(id) ON DELETE CASCADE;
alter table public.insolvency_creditors add constraint insolvency_creditors_updated_by_fkey FOREIGN KEY (updated_by) REFERENCES profiles(id) ON DELETE SET NULL;
alter table public.insolvency_filing_bundles add constraint insolvency_filing_bundles_case_id_fkey FOREIGN KEY (case_id) REFERENCES cases(id) ON DELETE CASCADE;
alter table public.insolvency_filing_bundles add constraint insolvency_filing_bundles_case_org_fk FOREIGN KEY (case_id, organization_id) REFERENCES cases(id, organization_id) ON DELETE CASCADE;
alter table public.insolvency_filing_bundles add constraint insolvency_filing_bundles_created_by_fkey FOREIGN KEY (created_by) REFERENCES profiles(id) ON DELETE SET NULL;
alter table public.insolvency_filing_bundles add constraint insolvency_filing_bundles_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES organizations(id) ON DELETE CASCADE;
alter table public.insolvency_filing_bundles add constraint insolvency_filing_bundles_plan_id_fkey FOREIGN KEY (plan_id) REFERENCES insolvency_repayment_plans(id) ON DELETE SET NULL;
alter table public.insolvency_priority_claims add constraint insolvency_priority_claims_case_id_fkey FOREIGN KEY (case_id) REFERENCES cases(id) ON DELETE CASCADE;
alter table public.insolvency_priority_claims add constraint insolvency_priority_claims_case_org_fk FOREIGN KEY (case_id, organization_id) REFERENCES cases(id, organization_id) ON DELETE CASCADE;
alter table public.insolvency_priority_claims add constraint insolvency_priority_claims_created_by_fkey FOREIGN KEY (created_by) REFERENCES profiles(id) ON DELETE SET NULL;
alter table public.insolvency_priority_claims add constraint insolvency_priority_claims_creditor_id_fkey FOREIGN KEY (creditor_id) REFERENCES insolvency_creditors(id) ON DELETE CASCADE;
alter table public.insolvency_priority_claims add constraint insolvency_priority_claims_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES organizations(id) ON DELETE CASCADE;
alter table public.insolvency_priority_claims add constraint insolvency_priority_claims_updated_by_fkey FOREIGN KEY (updated_by) REFERENCES profiles(id) ON DELETE SET NULL;
alter table public.insolvency_repayment_allocations add constraint insolvency_repayment_allocations_creditor_id_fkey FOREIGN KEY (creditor_id) REFERENCES insolvency_creditors(id) ON DELETE CASCADE;
alter table public.insolvency_repayment_allocations add constraint insolvency_repayment_allocations_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES organizations(id) ON DELETE CASCADE;
alter table public.insolvency_repayment_allocations add constraint insolvency_repayment_allocations_plan_id_fkey FOREIGN KEY (plan_id) REFERENCES insolvency_repayment_plans(id) ON DELETE CASCADE;
alter table public.insolvency_repayment_plans add constraint insolvency_repayment_plans_case_id_fkey FOREIGN KEY (case_id) REFERENCES cases(id) ON DELETE CASCADE;
alter table public.insolvency_repayment_plans add constraint insolvency_repayment_plans_case_org_fk FOREIGN KEY (case_id, organization_id) REFERENCES cases(id, organization_id) ON DELETE CASCADE;
alter table public.insolvency_repayment_plans add constraint insolvency_repayment_plans_confirmed_by_fkey FOREIGN KEY (confirmed_by) REFERENCES profiles(id) ON DELETE SET NULL;
alter table public.insolvency_repayment_plans add constraint insolvency_repayment_plans_created_by_fkey FOREIGN KEY (created_by) REFERENCES profiles(id) ON DELETE SET NULL;
alter table public.insolvency_repayment_plans add constraint insolvency_repayment_plans_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES organizations(id) ON DELETE CASCADE;
alter table public.insolvency_repayment_plans add constraint insolvency_repayment_plans_updated_by_fkey FOREIGN KEY (updated_by) REFERENCES profiles(id) ON DELETE SET NULL;
alter table public.invitations add constraint invitations_accepted_by_fkey FOREIGN KEY (accepted_by) REFERENCES profiles(id) ON DELETE SET NULL;
alter table public.invitations add constraint invitations_case_client_id_fkey FOREIGN KEY (case_client_id) REFERENCES case_clients(id) ON DELETE SET NULL;
alter table public.invitations add constraint invitations_case_id_fkey FOREIGN KEY (case_id) REFERENCES cases(id) ON DELETE CASCADE;
alter table public.invitations add constraint invitations_created_by_fkey FOREIGN KEY (created_by) REFERENCES profiles(id) ON DELETE SET NULL;
alter table public.invitations add constraint invitations_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES organizations(id) ON DELETE CASCADE;
alter table public.invoice_items add constraint invoice_items_billing_entry_id_fkey FOREIGN KEY (billing_entry_id) REFERENCES billing_entries(id) ON DELETE SET NULL;
alter table public.invoice_items add constraint invoice_items_invoice_id_fkey FOREIGN KEY (invoice_id) REFERENCES invoices(id) ON DELETE CASCADE;
alter table public.invoices add constraint invoices_bill_to_case_client_id_fkey FOREIGN KEY (bill_to_case_client_id) REFERENCES case_clients(id) ON DELETE SET NULL;
alter table public.invoices add constraint invoices_bill_to_case_organization_id_fkey FOREIGN KEY (bill_to_case_organization_id) REFERENCES case_organizations(id) ON DELETE SET NULL;
alter table public.invoices add constraint invoices_billing_owner_case_organization_id_fkey FOREIGN KEY (billing_owner_case_organization_id) REFERENCES case_organizations(id) ON DELETE CASCADE;
alter table public.invoices add constraint invoices_case_id_fkey FOREIGN KEY (case_id) REFERENCES cases(id) ON DELETE CASCADE;
alter table public.invoices add constraint invoices_created_by_fkey FOREIGN KEY (created_by) REFERENCES profiles(id) ON DELETE SET NULL;
alter table public.invoices add constraint invoices_updated_by_fkey FOREIGN KEY (updated_by) REFERENCES profiles(id) ON DELETE SET NULL;
alter table public.kakao_notification_outbox add constraint kakao_notification_outbox_notification_id_fkey FOREIGN KEY (notification_id) REFERENCES notifications(id) ON DELETE CASCADE;
alter table public.kakao_notification_outbox add constraint kakao_notification_outbox_recipient_profile_id_fkey FOREIGN KEY (recipient_profile_id) REFERENCES profiles(id) ON DELETE CASCADE;
alter table public.member_private_profiles add constraint member_private_profiles_profile_id_fkey FOREIGN KEY (profile_id) REFERENCES profiles(id) ON DELETE CASCADE;
alter table public.notification_channel_preferences add constraint notification_channel_preferences_profile_id_fkey FOREIGN KEY (profile_id) REFERENCES profiles(id) ON DELETE CASCADE;
alter table public.notifications add constraint notifications_case_id_fkey FOREIGN KEY (case_id) REFERENCES cases(id) ON DELETE CASCADE;
alter table public.notifications add constraint notifications_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES organizations(id) ON DELETE CASCADE;
alter table public.notifications add constraint notifications_recipient_profile_id_fkey FOREIGN KEY (recipient_profile_id) REFERENCES profiles(id) ON DELETE CASCADE;
alter table public.notifications add constraint notifications_trashed_by_fkey FOREIGN KEY (trashed_by) REFERENCES profiles(id) ON DELETE SET NULL;
alter table public.org_settlement_entries add constraint org_settlement_entries_case_id_fkey FOREIGN KEY (case_id) REFERENCES cases(id) ON DELETE SET NULL;
alter table public.org_settlement_entries add constraint org_settlement_entries_created_by_fkey FOREIGN KEY (created_by) REFERENCES profiles(id) ON DELETE SET NULL;
alter table public.org_settlement_entries add constraint org_settlement_entries_source_case_organization_id_fkey FOREIGN KEY (source_case_organization_id) REFERENCES case_organizations(id) ON DELETE CASCADE;
alter table public.org_settlement_entries add constraint org_settlement_entries_target_case_organization_id_fkey FOREIGN KEY (target_case_organization_id) REFERENCES case_organizations(id) ON DELETE CASCADE;
alter table public.org_settlement_entries add constraint org_settlement_entries_updated_by_fkey FOREIGN KEY (updated_by) REFERENCES profiles(id) ON DELETE SET NULL;
alter table public.organization_collaboration_case_shares add constraint organization_collaboration_case__shared_by_organization_id_fkey FOREIGN KEY (shared_by_organization_id) REFERENCES organizations(id) ON DELETE CASCADE;
alter table public.organization_collaboration_case_shares add constraint organization_collaboration_case_share_shared_by_profile_id_fkey FOREIGN KEY (shared_by_profile_id) REFERENCES profiles(id) ON DELETE CASCADE;
alter table public.organization_collaboration_case_shares add constraint organization_collaboration_case_shares_case_id_fkey FOREIGN KEY (case_id) REFERENCES cases(id) ON DELETE CASCADE;
alter table public.organization_collaboration_case_shares add constraint organization_collaboration_case_shares_hub_id_fkey FOREIGN KEY (hub_id) REFERENCES organization_collaboration_hubs(id) ON DELETE CASCADE;
alter table public.organization_collaboration_hubs add constraint organization_collaboration_hubs_created_by_profile_id_fkey FOREIGN KEY (created_by_profile_id) REFERENCES profiles(id) ON DELETE SET NULL;
alter table public.organization_collaboration_hubs add constraint organization_collaboration_hubs_partner_organization_id_fkey FOREIGN KEY (partner_organization_id) REFERENCES organizations(id) ON DELETE CASCADE;
alter table public.organization_collaboration_hubs add constraint organization_collaboration_hubs_primary_organization_id_fkey FOREIGN KEY (primary_organization_id) REFERENCES organizations(id) ON DELETE CASCADE;
alter table public.organization_collaboration_hubs add constraint organization_collaboration_hubs_request_id_fkey FOREIGN KEY (request_id) REFERENCES organization_collaboration_requests(id) ON DELETE SET NULL;
alter table public.organization_collaboration_messages add constraint organization_collaboration_messages_case_id_fkey FOREIGN KEY (case_id) REFERENCES cases(id) ON DELETE SET NULL;
alter table public.organization_collaboration_messages add constraint organization_collaboration_messages_hub_id_fkey FOREIGN KEY (hub_id) REFERENCES organization_collaboration_hubs(id) ON DELETE CASCADE;
alter table public.organization_collaboration_messages add constraint organization_collaboration_messages_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES organizations(id) ON DELETE CASCADE;
alter table public.organization_collaboration_messages add constraint organization_collaboration_messages_sender_profile_id_fkey FOREIGN KEY (sender_profile_id) REFERENCES profiles(id) ON DELETE CASCADE;
alter table public.organization_collaboration_reads add constraint organization_collaboration_reads_hub_id_fkey FOREIGN KEY (hub_id) REFERENCES organization_collaboration_hubs(id) ON DELETE CASCADE;
alter table public.organization_collaboration_reads add constraint organization_collaboration_reads_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES organizations(id) ON DELETE CASCADE;
alter table public.organization_collaboration_reads add constraint organization_collaboration_reads_profile_id_fkey FOREIGN KEY (profile_id) REFERENCES profiles(id) ON DELETE CASCADE;
alter table public.organization_collaboration_requests add constraint organization_collaboration_request_requested_by_profile_id_fkey FOREIGN KEY (requested_by_profile_id) REFERENCES profiles(id) ON DELETE CASCADE;
alter table public.organization_collaboration_requests add constraint organization_collaboration_requests_approved_hub_id_fkey FOREIGN KEY (approved_hub_id) REFERENCES organization_collaboration_hubs(id) ON DELETE SET NULL NOT VALID;
alter table public.organization_collaboration_requests add constraint organization_collaboration_requests_reviewed_by_profile_id_fkey FOREIGN KEY (reviewed_by_profile_id) REFERENCES profiles(id) ON DELETE SET NULL;
alter table public.organization_collaboration_requests add constraint organization_collaboration_requests_source_organization_id_fkey FOREIGN KEY (source_organization_id) REFERENCES organizations(id) ON DELETE CASCADE;
alter table public.organization_collaboration_requests add constraint organization_collaboration_requests_target_organization_id_fkey FOREIGN KEY (target_organization_id) REFERENCES organizations(id) ON DELETE CASCADE;
alter table public.organization_exit_requests add constraint organization_exit_requests_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES organizations(id) ON DELETE CASCADE;
alter table public.organization_exit_requests add constraint organization_exit_requests_requested_by_profile_id_fkey FOREIGN KEY (requested_by_profile_id) REFERENCES profiles(id) ON DELETE RESTRICT;
alter table public.organization_exit_requests add constraint organization_exit_requests_reviewed_by_profile_id_fkey FOREIGN KEY (reviewed_by_profile_id) REFERENCES profiles(id) ON DELETE SET NULL;
alter table public.organization_membership_permission_overrides add constraint organization_membership_permiss_organization_membership_id_fkey FOREIGN KEY (organization_membership_id) REFERENCES organization_memberships(id) ON DELETE CASCADE;
alter table public.organization_membership_permission_overrides add constraint organization_membership_permission_overrides_created_by_fkey FOREIGN KEY (created_by) REFERENCES profiles(id) ON DELETE SET NULL;
alter table public.organization_memberships add constraint organization_memberships_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES organizations(id) ON DELETE CASCADE;
alter table public.organization_memberships add constraint organization_memberships_profile_id_fkey FOREIGN KEY (profile_id) REFERENCES profiles(id) ON DELETE CASCADE;
alter table public.organization_relations add constraint organization_relations_created_by_fkey FOREIGN KEY (created_by) REFERENCES profiles(id) ON DELETE SET NULL;
alter table public.organization_relations add constraint organization_relations_source_organization_id_fkey FOREIGN KEY (source_organization_id) REFERENCES organizations(id) ON DELETE CASCADE;
alter table public.organization_relations add constraint organization_relations_target_organization_id_fkey FOREIGN KEY (target_organization_id) REFERENCES organizations(id) ON DELETE CASCADE;
alter table public.organization_settings add constraint organization_settings_key_fkey FOREIGN KEY (key) REFERENCES setting_catalog(key) ON DELETE CASCADE;
alter table public.organization_settings add constraint organization_settings_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES organizations(id) ON DELETE CASCADE;
alter table public.organization_settings add constraint organization_settings_updated_by_fkey FOREIGN KEY (updated_by) REFERENCES profiles(id) ON DELETE SET NULL;
alter table public.organization_signup_requests add constraint organization_signup_requests_approval_locked_by_profile_id_fkey FOREIGN KEY (approval_locked_by_profile_id) REFERENCES profiles(id) ON DELETE SET NULL;
alter table public.organization_signup_requests add constraint organization_signup_requests_approved_organization_id_fkey FOREIGN KEY (approved_organization_id) REFERENCES organizations(id) ON DELETE SET NULL;
alter table public.organization_signup_requests add constraint organization_signup_requests_requester_profile_id_fkey FOREIGN KEY (requester_profile_id) REFERENCES profiles(id) ON DELETE SET NULL;
alter table public.organization_signup_requests add constraint organization_signup_requests_reviewed_by_fkey FOREIGN KEY (reviewed_by) REFERENCES profiles(id) ON DELETE SET NULL;
alter table public.organization_staff_temp_credentials add constraint organization_staff_temp_credentials_issued_by_fkey FOREIGN KEY (issued_by) REFERENCES profiles(id) ON DELETE SET NULL;
alter table public.organization_staff_temp_credentials add constraint organization_staff_temp_credentials_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES organizations(id) ON DELETE CASCADE;
alter table public.organization_staff_temp_credentials add constraint organization_staff_temp_credentials_profile_id_fkey FOREIGN KEY (profile_id) REFERENCES profiles(id) ON DELETE CASCADE;
alter table public.organization_subscription_states add constraint organization_subscription_states_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES organizations(id) ON DELETE CASCADE;
alter table public.organization_subscription_states add constraint organization_subscription_states_updated_by_fkey FOREIGN KEY (updated_by) REFERENCES profiles(id) ON DELETE SET NULL;
alter table public.organizations add constraint organizations_created_by_fkey FOREIGN KEY (created_by) REFERENCES profiles(id) ON DELETE SET NULL;
alter table public.organizations add constraint organizations_source_signup_request_id_fkey FOREIGN KEY (source_signup_request_id) REFERENCES organization_signup_requests(id) ON DELETE SET NULL;
alter table public.payment_allocations add constraint payment_allocations_invoice_id_fkey FOREIGN KEY (invoice_id) REFERENCES invoices(id) ON DELETE CASCADE;
alter table public.payment_allocations add constraint payment_allocations_invoice_item_id_fkey FOREIGN KEY (invoice_item_id) REFERENCES invoice_items(id) ON DELETE SET NULL;
alter table public.payment_allocations add constraint payment_allocations_payment_id_fkey FOREIGN KEY (payment_id) REFERENCES payments(id) ON DELETE CASCADE;
alter table public.payments add constraint payments_billing_owner_case_organization_id_fkey FOREIGN KEY (billing_owner_case_organization_id) REFERENCES case_organizations(id) ON DELETE CASCADE;
alter table public.payments add constraint payments_case_id_fkey FOREIGN KEY (case_id) REFERENCES cases(id) ON DELETE CASCADE;
alter table public.payments add constraint payments_confirmed_by_fkey FOREIGN KEY (confirmed_by) REFERENCES profiles(id) ON DELETE SET NULL;
alter table public.payments add constraint payments_created_by_fkey FOREIGN KEY (created_by) REFERENCES profiles(id) ON DELETE SET NULL;
alter table public.payments add constraint payments_payer_case_client_id_fkey FOREIGN KEY (payer_case_client_id) REFERENCES case_clients(id) ON DELETE SET NULL;
alter table public.payments add constraint payments_payer_case_organization_id_fkey FOREIGN KEY (payer_case_organization_id) REFERENCES case_organizations(id) ON DELETE SET NULL;
alter table public.payments add constraint payments_updated_by_fkey FOREIGN KEY (updated_by) REFERENCES profiles(id) ON DELETE SET NULL;
alter table public.permission_template_items add constraint permission_template_items_template_key_fkey FOREIGN KEY (template_key) REFERENCES permission_templates(key) ON DELETE CASCADE;
alter table public.platform_runtime_settings add constraint platform_runtime_settings_platform_organization_id_fkey FOREIGN KEY (platform_organization_id) REFERENCES organizations(id) ON DELETE RESTRICT;
alter table public.platform_settings add constraint platform_settings_key_fkey FOREIGN KEY (key) REFERENCES setting_catalog(key) ON DELETE CASCADE;
alter table public.platform_settings add constraint platform_settings_updated_by_fkey FOREIGN KEY (updated_by) REFERENCES profiles(id) ON DELETE SET NULL;
alter table public.profiles add constraint profiles_default_organization_fk FOREIGN KEY (default_organization_id) REFERENCES organizations(id) ON DELETE SET NULL;
alter table public.profiles add constraint profiles_id_fkey FOREIGN KEY (id) REFERENCES auth.users(id) ON DELETE CASCADE;
alter table public.rehabilitation_affidavits add constraint rehab_affidavits_case_org_fk FOREIGN KEY (case_id, organization_id) REFERENCES cases(id, organization_id) ON DELETE CASCADE;
alter table public.rehabilitation_affidavits add constraint rehabilitation_affidavits_case_id_fkey FOREIGN KEY (case_id) REFERENCES cases(id) ON DELETE CASCADE;
alter table public.rehabilitation_applications add constraint rehab_applications_case_org_fk FOREIGN KEY (case_id, organization_id) REFERENCES cases(id, organization_id) ON DELETE CASCADE;
alter table public.rehabilitation_applications add constraint rehabilitation_applications_case_id_fkey FOREIGN KEY (case_id) REFERENCES cases(id) ON DELETE CASCADE;
alter table public.rehabilitation_applications add constraint rehabilitation_applications_created_by_fkey FOREIGN KEY (created_by) REFERENCES profiles(id) ON DELETE SET NULL;
alter table public.rehabilitation_applications add constraint rehabilitation_applications_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES organizations(id) ON DELETE CASCADE;
alter table public.rehabilitation_applications add constraint rehabilitation_applications_updated_by_fkey FOREIGN KEY (updated_by) REFERENCES profiles(id) ON DELETE SET NULL;
alter table public.rehabilitation_creditor_settings add constraint rehab_cred_settings_case_org_fk FOREIGN KEY (case_id, organization_id) REFERENCES cases(id, organization_id) ON DELETE CASCADE;
alter table public.rehabilitation_creditor_settings add constraint rehabilitation_creditor_settings_case_id_fkey FOREIGN KEY (case_id) REFERENCES cases(id) ON DELETE CASCADE;
alter table public.rehabilitation_creditors add constraint rehab_creditors_case_org_fk FOREIGN KEY (case_id, organization_id) REFERENCES cases(id, organization_id) ON DELETE CASCADE;
alter table public.rehabilitation_creditors add constraint rehabilitation_creditors_case_id_fkey FOREIGN KEY (case_id) REFERENCES cases(id) ON DELETE CASCADE;
alter table public.rehabilitation_creditors add constraint rehabilitation_creditors_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES organizations(id) ON DELETE CASCADE;
alter table public.rehabilitation_creditors add constraint rehabilitation_creditors_secured_property_id_fkey FOREIGN KEY (secured_property_id) REFERENCES rehabilitation_secured_properties(id) ON DELETE SET NULL;
alter table public.rehabilitation_family_members add constraint rehab_family_case_org_fk FOREIGN KEY (case_id, organization_id) REFERENCES cases(id, organization_id) ON DELETE CASCADE;
alter table public.rehabilitation_family_members add constraint rehabilitation_family_members_case_id_fkey FOREIGN KEY (case_id) REFERENCES cases(id) ON DELETE CASCADE;
alter table public.rehabilitation_income_settings add constraint rehab_income_case_org_fk FOREIGN KEY (case_id, organization_id) REFERENCES cases(id, organization_id) ON DELETE CASCADE;
alter table public.rehabilitation_income_settings add constraint rehabilitation_income_settings_case_id_fkey FOREIGN KEY (case_id) REFERENCES cases(id) ON DELETE CASCADE;
alter table public.rehabilitation_plan_sections add constraint rehab_plan_case_org_fk FOREIGN KEY (case_id, organization_id) REFERENCES cases(id, organization_id) ON DELETE CASCADE;
alter table public.rehabilitation_plan_sections add constraint rehabilitation_plan_sections_case_id_fkey FOREIGN KEY (case_id) REFERENCES cases(id) ON DELETE CASCADE;
alter table public.rehabilitation_prohibition_orders add constraint rehab_prohibition_case_org_fk FOREIGN KEY (case_id, organization_id) REFERENCES cases(id, organization_id) ON DELETE CASCADE;
alter table public.rehabilitation_prohibition_orders add constraint rehabilitation_prohibition_orders_case_id_fkey FOREIGN KEY (case_id) REFERENCES cases(id) ON DELETE CASCADE;
alter table public.rehabilitation_prohibition_orders add constraint rehabilitation_prohibition_orders_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES organizations(id) ON DELETE CASCADE;
alter table public.rehabilitation_properties add constraint rehab_properties_case_org_fk FOREIGN KEY (case_id, organization_id) REFERENCES cases(id, organization_id) ON DELETE CASCADE;
alter table public.rehabilitation_properties add constraint rehabilitation_properties_case_id_fkey FOREIGN KEY (case_id) REFERENCES cases(id) ON DELETE CASCADE;
alter table public.rehabilitation_properties add constraint rehabilitation_properties_secured_property_id_fkey FOREIGN KEY (secured_property_id) REFERENCES rehabilitation_secured_properties(id) ON DELETE SET NULL;
alter table public.rehabilitation_property_deductions add constraint rehab_prop_deductions_case_org_fk FOREIGN KEY (case_id, organization_id) REFERENCES cases(id, organization_id) ON DELETE CASCADE;
alter table public.rehabilitation_property_deductions add constraint rehabilitation_property_deductions_case_id_fkey FOREIGN KEY (case_id) REFERENCES cases(id) ON DELETE CASCADE;
alter table public.rehabilitation_secured_properties add constraint rehab_secured_case_org_fk FOREIGN KEY (case_id, organization_id) REFERENCES cases(id, organization_id) ON DELETE CASCADE;
alter table public.rehabilitation_secured_properties add constraint rehabilitation_secured_properties_case_id_fkey FOREIGN KEY (case_id) REFERENCES cases(id) ON DELETE CASCADE;
alter table public.setting_change_logs add constraint setting_change_logs_changed_by_fkey FOREIGN KEY (changed_by) REFERENCES profiles(id) ON DELETE SET NULL;
alter table public.setting_change_logs add constraint setting_change_logs_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES organizations(id) ON DELETE CASCADE;
alter table public.setting_change_logs add constraint setting_change_logs_rolled_back_from_log_id_fkey FOREIGN KEY (rolled_back_from_log_id) REFERENCES setting_change_logs(id) ON DELETE SET NULL;
alter table public.support_access_requests add constraint support_access_requests_approved_by_fkey FOREIGN KEY (approved_by) REFERENCES profiles(id) ON DELETE SET NULL;
alter table public.support_access_requests add constraint support_access_requests_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES organizations(id) ON DELETE CASCADE;
alter table public.support_access_requests add constraint support_access_requests_requested_by_fkey FOREIGN KEY (requested_by) REFERENCES profiles(id) ON DELETE CASCADE;
alter table public.support_access_requests add constraint support_access_requests_target_profile_id_fkey FOREIGN KEY (target_profile_id) REFERENCES profiles(id) ON DELETE CASCADE;
