-- ============================================================
-- 007_indexes.sql
-- Regenerated squash — Batch 7: non-PK/non-UNIQUE indexes
-- Requires: tables (Batch 2) exist. Idempotent via DROP IF EXISTS.
-- ============================================================

CREATE INDEX IF NOT EXISTS idx_audit_actor_logged_at ON audit.change_log USING btree (actor_user_id, logged_at DESC);
CREATE INDEX IF NOT EXISTS idx_audit_case_logged_at ON audit.change_log USING btree (case_id, logged_at DESC);
CREATE INDEX IF NOT EXISTS idx_audit_org_logged_at ON audit.change_log USING btree (organization_id, logged_at DESC);
CREATE INDEX IF NOT EXISTS idx_billing_entries_case_status ON public.billing_entries USING btree (case_id, status, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_billing_entries_case_v2 ON public.billing_entries USING btree (case_id, status, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_billing_subscription_events_org ON public.billing_subscription_events USING btree (organization_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_case_clients_case ON public.case_clients USING btree (case_id);
CREATE INDEX IF NOT EXISTS idx_case_clients_case_link_status ON public.case_clients USING btree (case_id, link_status);
CREATE INDEX IF NOT EXISTS idx_case_clients_last_linked_hub_id ON public.case_clients USING btree (last_linked_hub_id) WHERE (last_linked_hub_id IS NOT NULL);
CREATE INDEX IF NOT EXISTS idx_case_clients_orphan_review_deadline ON public.case_clients USING btree (review_deadline) WHERE (link_status = 'orphan_review'::case_client_link_status);
CREATE INDEX IF NOT EXISTS idx_case_clients_profile ON public.case_clients USING btree (profile_id);
CREATE INDEX IF NOT EXISTS idx_case_document_reviews_case ON public.case_document_reviews USING btree (case_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_case_documents_case ON public.case_documents USING btree (case_id, updated_at DESC);
CREATE INDEX IF NOT EXISTS idx_case_documents_generated ON public.case_documents USING btree (case_id, source_kind, source_document_type, created_at DESC) WHERE (source_kind IS NOT NULL);
CREATE INDEX IF NOT EXISTS idx_case_documents_status ON public.case_documents USING btree (organization_id, approval_status);
CREATE INDEX IF NOT EXISTS idx_case_handlers_case ON public.case_handlers USING btree (case_id);
CREATE INDEX IF NOT EXISTS idx_case_hub_activity_created ON public.case_hub_activity USING btree (created_at DESC);
CREATE INDEX IF NOT EXISTS idx_case_hub_activity_hub_id ON public.case_hub_activity USING btree (hub_id);
CREATE INDEX IF NOT EXISTS idx_case_hub_members_hub_id ON public.case_hub_members USING btree (hub_id);
CREATE INDEX IF NOT EXISTS idx_case_hub_members_profile ON public.case_hub_members USING btree (profile_id);
CREATE INDEX IF NOT EXISTS idx_case_hub_organizations_case_org ON public.case_hub_organizations USING btree (source_case_organization_id);
CREATE INDEX IF NOT EXISTS idx_case_hub_organizations_hub ON public.case_hub_organizations USING btree (hub_id, status);
CREATE INDEX IF NOT EXISTS idx_case_hub_organizations_org ON public.case_hub_organizations USING btree (organization_id, status);
CREATE INDEX IF NOT EXISTS idx_case_hubs_case_id ON public.case_hubs USING btree (case_id);
CREATE INDEX IF NOT EXISTS idx_case_hubs_lifecycle ON public.case_hubs USING btree (lifecycle_status);
CREATE INDEX IF NOT EXISTS idx_case_hubs_organization_id ON public.case_hubs USING btree (organization_id);
CREATE INDEX IF NOT EXISTS idx_case_hubs_primary_case_client_id ON public.case_hubs USING btree (primary_case_client_id) WHERE (primary_case_client_id IS NOT NULL);
CREATE INDEX IF NOT EXISTS idx_case_messages_case_created ON public.case_messages USING btree (case_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_case_organizations_case ON public.case_organizations USING btree (case_id, status, role);
CREATE INDEX IF NOT EXISTS idx_case_organizations_instructed_by ON public.case_organizations USING btree (instructed_by_case_organization_id);
CREATE INDEX IF NOT EXISTS idx_case_organizations_org ON public.case_organizations USING btree (organization_id, status, role);
CREATE INDEX IF NOT EXISTS idx_case_parties_case ON public.case_parties USING btree (case_id);
CREATE INDEX IF NOT EXISTS idx_case_recovery_case ON public.case_recovery_activities USING btree (case_id, occurred_at DESC);
CREATE INDEX IF NOT EXISTS idx_case_requests_assigned ON public.case_requests USING btree (assigned_to, status, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_case_requests_case_status ON public.case_requests USING btree (case_id, status, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_case_schedules_case ON public.case_schedules USING btree (case_id, scheduled_start);
CREATE INDEX IF NOT EXISTS idx_case_schedules_org_due ON public.case_schedules USING btree (organization_id, scheduled_start);
CREATE INDEX IF NOT EXISTS idx_cases_insolvency_subtype ON public.cases USING btree (organization_id, insolvency_subtype) WHERE (case_type = 'insolvency'::case_type);
CREATE INDEX IF NOT EXISTS idx_cases_org ON public.cases USING btree (organization_id, updated_at DESC);
CREATE INDEX IF NOT EXISTS idx_cases_status ON public.cases USING btree (organization_id, case_status);
CREATE UNIQUE INDEX IF NOT EXISTS ux_cases_colaw_case_basic_seq ON public.cases USING btree (colaw_case_basic_seq) WHERE (colaw_case_basic_seq IS NOT NULL);
CREATE INDEX IF NOT EXISTS idx_client_access_requests_requester_status ON public.client_access_requests USING btree (requester_profile_id, status, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_client_access_requests_target_status ON public.client_access_requests USING btree (target_organization_id, status, created_at DESC);
CREATE UNIQUE INDEX IF NOT EXISTS uq_client_access_requests_pending ON public.client_access_requests USING btree (target_organization_id, requester_profile_id) WHERE (status = 'pending'::client_access_request_status);
CREATE INDEX IF NOT EXISTS idx_client_private_profiles_created_at ON public.client_private_profiles USING btree (created_at DESC);
CREATE INDEX IF NOT EXISTS idx_client_service_requests_org_status ON public.client_service_requests USING btree (organization_id, status, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_client_service_requests_profile_status ON public.client_service_requests USING btree (profile_id, status, created_at DESC);
CREATE INDEX IF NOT EXISTS client_temp_credentials_case_idx ON public.client_temp_credentials USING btree (case_id, created_at DESC);
CREATE INDEX IF NOT EXISTS client_temp_credentials_org_idx ON public.client_temp_credentials USING btree (organization_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_comp_entries_case_period ON public.collection_compensation_entries USING btree (case_id, period_start DESC);
CREATE INDEX IF NOT EXISTS idx_comp_plans_case ON public.collection_compensation_plans USING btree (case_id, is_active);
CREATE INDEX IF NOT EXISTS idx_performance_daily_date ON public.collection_performance_daily USING btree (performance_date DESC);
CREATE UNIQUE INDEX IF NOT EXISTS uq_content_resources_published ON public.content_resources USING btree (namespace, resource_key, locale, COALESCE(organization_id, '00000000-0000-0000-0000-000000000000'::uuid), status);
CREATE INDEX IF NOT EXISTS idx_ingestion_jobs_case ON public.document_ingestion_jobs USING btree (case_id, status);
CREATE INDEX IF NOT EXISTS idx_ingestion_jobs_org_status ON public.document_ingestion_jobs USING btree (organization_id, status, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_ingestion_jobs_pending ON public.document_ingestion_jobs USING btree (status, created_at) WHERE (status = ANY (ARRAY['pending'::ingestion_status, 'failed'::ingestion_status]));
CREATE INDEX IF NOT EXISTS idx_feature_flags_org_key ON public.feature_flags USING btree (organization_id, flag_key);
CREATE UNIQUE INDEX IF NOT EXISTS uq_feature_flags_scope ON public.feature_flags USING btree (flag_key, COALESCE(organization_id, '00000000-0000-0000-0000-000000000000'::uuid));
CREATE INDEX IF NOT EXISTS idx_fee_agreements_case ON public.fee_agreements USING btree (case_id, is_active);
CREATE INDEX IF NOT EXISTS idx_action_items_case ON public.insolvency_client_action_items USING btree (case_id, is_completed);
CREATE INDEX IF NOT EXISTS idx_action_items_packet ON public.insolvency_client_action_items USING btree (packet_id, display_order);
CREATE INDEX IF NOT EXISTS idx_action_packets_case ON public.insolvency_client_action_packets USING btree (case_id, status);
CREATE INDEX IF NOT EXISTS idx_insolvency_collaterals_case ON public.insolvency_collaterals USING btree (case_id, lifecycle_status);
CREATE INDEX IF NOT EXISTS idx_insolvency_collaterals_creditor ON public.insolvency_collaterals USING btree (creditor_id);
CREATE INDEX IF NOT EXISTS idx_insolvency_creditor_addresses_creditor ON public.insolvency_creditor_addresses USING btree (creditor_id);
CREATE INDEX IF NOT EXISTS idx_insolvency_creditors_case ON public.insolvency_creditors USING btree (case_id, lifecycle_status, claim_class);
CREATE INDEX IF NOT EXISTS idx_insolvency_creditors_org ON public.insolvency_creditors USING btree (organization_id, lifecycle_status);
CREATE INDEX IF NOT EXISTS idx_filing_bundles_case ON public.insolvency_filing_bundles USING btree (case_id, status);
CREATE INDEX IF NOT EXISTS idx_priority_claims_case ON public.insolvency_priority_claims USING btree (case_id, lifecycle_status);
CREATE INDEX IF NOT EXISTS idx_priority_claims_creditor ON public.insolvency_priority_claims USING btree (creditor_id);
CREATE INDEX IF NOT EXISTS idx_repayment_allocations_creditor ON public.insolvency_repayment_allocations USING btree (creditor_id);
CREATE INDEX IF NOT EXISTS idx_repayment_allocations_plan ON public.insolvency_repayment_allocations USING btree (plan_id);
CREATE INDEX IF NOT EXISTS idx_repayment_plans_case ON public.insolvency_repayment_plans USING btree (case_id, status);
CREATE INDEX IF NOT EXISTS idx_ruleset_constants_key ON public.insolvency_ruleset_constants USING btree (ruleset_key, effective_from);
CREATE INDEX IF NOT EXISTS idx_invitations_case_client ON public.invitations USING btree (case_client_id, status);
CREATE INDEX IF NOT EXISTS idx_invitations_case_status ON public.invitations USING btree (case_id, status, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_invitations_org_status ON public.invitations USING btree (organization_id, status, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_invitations_status_expires ON public.invitations USING btree (status, expires_at);
CREATE INDEX IF NOT EXISTS idx_invitations_token_hash_status ON public.invitations USING btree (token_hash, status);
CREATE INDEX IF NOT EXISTS idx_invoices_case_status ON public.invoices USING btree (case_id, status, created_at DESC);
CREATE INDEX IF NOT EXISTS kakao_notification_outbox_status_idx ON public.kakao_notification_outbox USING btree (status, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_notifications_recipient ON public.notifications USING btree (recipient_profile_id, created_at DESC);
CREATE INDEX IF NOT EXISTS notifications_action_pending_idx ON public.notifications USING btree (recipient_profile_id, organization_id, action_entity_type, action_target_id) WHERE ((requires_action = true) AND (resolved_at IS NULL));
CREATE INDEX IF NOT EXISTS notifications_destination_idx ON public.notifications USING btree (recipient_profile_id, destination_url, created_at DESC) WHERE (status = ANY (ARRAY['active'::text, 'read'::text]));
CREATE INDEX IF NOT EXISTS notifications_queue_entity_idx ON public.notifications USING btree (recipient_profile_id, entity_type, entity_id, created_at DESC) WHERE (status <> 'deleted'::text);
CREATE INDEX IF NOT EXISTS notifications_queue_status_priority_idx ON public.notifications USING btree (recipient_profile_id, status, priority, created_at DESC) WHERE (status = ANY (ARRAY['active'::text, 'read'::text, 'resolved'::text, 'archived'::text]));
CREATE INDEX IF NOT EXISTS notifications_recipient_active_idx ON public.notifications USING btree (recipient_profile_id, created_at DESC) WHERE (trashed_at IS NULL);
CREATE INDEX IF NOT EXISTS notifications_recipient_trash_idx ON public.notifications USING btree (recipient_profile_id, trashed_at DESC) WHERE (trashed_at IS NOT NULL);
CREATE INDEX IF NOT EXISTS notifications_snooze_queue_idx ON public.notifications USING btree (recipient_profile_id, snoozed_until, created_at DESC) WHERE (trashed_at IS NULL);
CREATE INDEX IF NOT EXISTS idx_org_settlement_case_status ON public.org_settlement_entries USING btree (case_id, status, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_org_collaboration_case_shares_hub_created_at ON public.organization_collaboration_case_shares USING btree (hub_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_org_collaboration_hubs_partner_status ON public.organization_collaboration_hubs USING btree (partner_organization_id, status, updated_at DESC);
CREATE INDEX IF NOT EXISTS idx_org_collaboration_hubs_primary_status ON public.organization_collaboration_hubs USING btree (primary_organization_id, status, updated_at DESC);
CREATE UNIQUE INDEX IF NOT EXISTS uq_org_collaboration_hubs_active_pair ON public.organization_collaboration_hubs USING btree (LEAST(primary_organization_id, partner_organization_id), GREATEST(primary_organization_id, partner_organization_id)) WHERE (status = 'active'::text);
CREATE INDEX IF NOT EXISTS idx_org_collaboration_messages_hub_created_at ON public.organization_collaboration_messages USING btree (hub_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_org_collaboration_messages_org_created_at ON public.organization_collaboration_messages USING btree (organization_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_org_collaboration_reads_hub_profile ON public.organization_collaboration_reads USING btree (hub_id, profile_id, last_read_at DESC);
CREATE INDEX IF NOT EXISTS idx_org_collaboration_requests_source_status ON public.organization_collaboration_requests USING btree (source_organization_id, status, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_org_collaboration_requests_target_status ON public.organization_collaboration_requests USING btree (target_organization_id, status, created_at DESC);
CREATE UNIQUE INDEX IF NOT EXISTS uq_org_collaboration_requests_pending_pair ON public.organization_collaboration_requests USING btree (source_organization_id, target_organization_id) WHERE (status = 'pending'::collaboration_request_status);
CREATE INDEX IF NOT EXISTS idx_org_exit_requests_org ON public.organization_exit_requests USING btree (organization_id, status, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_org_exit_requests_status ON public.organization_exit_requests USING btree (status, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_org_memberships_org ON public.organization_memberships USING btree (organization_id, status, role);
CREATE INDEX IF NOT EXISTS idx_org_memberships_profile ON public.organization_memberships USING btree (profile_id, status);
CREATE INDEX IF NOT EXISTS idx_organization_relations_source ON public.organization_relations USING btree (source_organization_id, relation_type);
CREATE INDEX IF NOT EXISTS idx_organization_relations_target ON public.organization_relations USING btree (target_organization_id, relation_type);
CREATE INDEX IF NOT EXISTS idx_org_settings_org_key ON public.organization_settings USING btree (organization_id, key);
CREATE INDEX IF NOT EXISTS idx_org_signup_requests_kind_status ON public.organization_signup_requests USING btree (organization_kind, status, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_org_signup_requests_verification_status ON public.organization_signup_requests USING btree (business_registration_verification_status, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_signup_requests_status_created ON public.organization_signup_requests USING btree (status, created_at DESC);
CREATE UNIQUE INDEX IF NOT EXISTS uq_org_signup_pending_requester ON public.organization_signup_requests USING btree (requester_profile_id) WHERE (status = 'pending'::organization_signup_status);
CREATE INDEX IF NOT EXISTS organization_staff_temp_credentials_org_created_idx ON public.organization_staff_temp_credentials USING btree (organization_id, created_at DESC);
CREATE UNIQUE INDEX IF NOT EXISTS organization_staff_temp_credentials_org_login_idx ON public.organization_staff_temp_credentials USING btree (organization_id, login_id_normalized);
CREATE INDEX IF NOT EXISTS idx_org_subscription_states_state ON public.organization_subscription_states USING btree (state, updated_at DESC);
CREATE UNIQUE INDEX IF NOT EXISTS organizations_single_platform_root_idx ON public.organizations USING btree (is_platform_root) WHERE (is_platform_root = true);
CREATE UNIQUE INDEX IF NOT EXISTS uq_organizations_platform_management_singleton ON public.organizations USING btree (kind) WHERE (kind = 'platform_management'::organization_kind);
CREATE UNIQUE INDEX IF NOT EXISTS uq_organizations_source_signup_request ON public.organizations USING btree (source_signup_request_id) WHERE (source_signup_request_id IS NOT NULL);
CREATE INDEX IF NOT EXISTS idx_payments_case_received ON public.payments USING btree (case_id, received_at DESC);
CREATE UNIQUE INDEX IF NOT EXISTS uq_platform_runtime_settings_platform_organization_id ON public.platform_runtime_settings USING btree (platform_organization_id);
CREATE INDEX IF NOT EXISTS idx_rate_limit_buckets_expires_at ON public.rate_limit_buckets USING btree (expires_at);
CREATE INDEX IF NOT EXISTS idx_rehab_app_case ON public.rehabilitation_applications USING btree (case_id);
CREATE INDEX IF NOT EXISTS idx_rehab_app_org ON public.rehabilitation_applications USING btree (organization_id);
CREATE INDEX IF NOT EXISTS idx_rehab_creditors_case ON public.rehabilitation_creditors USING btree (case_id, bond_number);
CREATE INDEX IF NOT EXISTS idx_rehab_creditors_org ON public.rehabilitation_creditors USING btree (organization_id);
CREATE INDEX IF NOT EXISTS idx_rehab_creditors_secured ON public.rehabilitation_creditors USING btree (case_id, is_secured) WHERE (is_secured = true);
CREATE INDEX IF NOT EXISTS idx_rehab_creditors_unconfirmed ON public.rehabilitation_creditors USING btree (case_id, is_other_unconfirmed) WHERE (is_other_unconfirmed = true);
CREATE INDEX IF NOT EXISTS idx_rehab_family_case ON public.rehabilitation_family_members USING btree (case_id);
CREATE INDEX IF NOT EXISTS idx_rehab_prohibition_case ON public.rehabilitation_prohibition_orders USING btree (case_id);
CREATE INDEX IF NOT EXISTS idx_rehab_properties_case ON public.rehabilitation_properties USING btree (case_id, category);
CREATE INDEX IF NOT EXISTS idx_rehab_secured_case ON public.rehabilitation_secured_properties USING btree (case_id);
CREATE INDEX IF NOT EXISTS idx_setting_change_logs_target ON public.setting_change_logs USING btree (target_type, target_key, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_support_requests_org ON public.support_access_requests USING btree (organization_id, status, created_at DESC);
